components:
    schemas:
        DataDefinition:
            description: https://www.schema.org/DataDefinition
            properties:
                contentSpaceId:
                    format: int64
                    type: integer
                dataDefinitionFields:
                    items:
                        $ref: '#/components/schemas/DataDefinitionField'
                    type: array
                dateCreated:
                    format: date-time
                    type: string
                dateModified:
                    format: date-time
                    type: string
                description:
                    items:
                        $ref: '#/components/schemas/LocalizedValue'
                    type: array
                id:
                    format: int64
                    type: integer
                name:
                    items:
                        $ref: '#/components/schemas/LocalizedValue'
                    type: array
                storageType:
                    type: string
                userId:
                    format: int64
                    type: integer
            type: object
        DataDefinitionField:
            properties:
                defaultValue:
                    type: string
                fieldType:
                    type: string
                id:
                    format: int64
                    type: integer
                indexable:
                    type: boolean
                label:
                    items:
                        $ref: '#/components/schemas/LocalizedValue'
                    type: array
                localizable:
                    type: boolean
                name:
                    type: string
                repeatable:
                    type: boolean
                tip:
                    items:
                        $ref: '#/components/schemas/LocalizedValue'
                    type: array
            type: object
        DataRecordCollection:
            description: https://www.schema.org/DataRecordCollection
            properties:
                dataDefinitionId:
                    format: int64
                    type: integer
                description:
                    items:
                        $ref: '#/components/schemas/LocalizedValue'
                    type: array
                id:
                    format: int64
                    type: integer
                name:
                    items:
                        $ref: '#/components/schemas/LocalizedValue'
                    type: array

            type: object
        LocalizedValue:
            description: https://www.schema.org/LocalizedValue
            properties:
                key:
                    type: string
                value:
                    type: string
info:
    description: ""
    title: ""
    version: v1.0
openapi: 3.0.1
paths:
    "/data-definitions":
        get:
            parameters:
                - in: query
                  name: page
                  required: true
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  required: true
                  schema:
                      type: integer
                - in: query
                  name: contentSpaceId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: keywords
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/DataDefinition"
                                type: array
                    description: ""
            tags: ["DataDefinition"]
        post:
            parameters:
                - in: query
                  name: contentSpaceId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DataDefinition"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/DataDefinition"
                    description: ""
            tags: ["DataDefinition"]
    "/data-definitions/{data-definition-id}":
        delete:
            parameters:
                - in: path
                  name: data-definition-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                    description: ""
            tags: ["DataDefinition"]
        get:
            parameters:
                - in: path
                  name: data-definition-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/DataDefinition"
                    description: ""
            tags: ["DataDefinition"]
        put:
            parameters:
                - in: path
                  name: data-definition-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DataDefinition"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/DataDefinition"
                    description: ""
            tags: ["DataDefinition"]
    "/data-record-collections":
        get:
            parameters:
                - in: query
                  name: page
                  required: true
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  required: true
                  schema:
                      type: integer
                - in: query
                  name: contentSpaceId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: keywords
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/DataRecordCollection"
                                type: array
                    description: ""
            tags: ["DataRecordCollection"]
        post:
            parameters:
                - in: query
                  name: contentSpaceId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DataRecordCollection"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/DataRecordCollection"
                    description: ""
            tags: ["DataRecordCollection"]
    "/data-record-collections/{data-record-collection-id}":
        delete:
            parameters:
                - in: path
                  name: data-record-collection-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                    description: ""
            tags: ["DataRecordCollection"]
        get:
            parameters:
                - in: path
                  name: data-record-collection-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/DataRecordCollection"
                    description: ""
            tags: ["DataRecordCollection"]
        put:
            parameters:
                - in: path
                  name: data-record-collection-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DataRecordCollection"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/DataRecordCollection"
                    description: ""
            tags: ["DataRecordCollection"]